name: sura_flutter
description: A flutter package from AsurRaa for widgets and utility functions
version: 0.0.5
homepage: https://github.com/asurraa/sura_flutter

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
